name: Windows Build and Release

on:
  push:
    tags:
      - "v*"  # Change this to your desired branch
  workflow_dispatch:  # Enables manual triggering

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Run build_exec.bat
        run: ./build_exec.bat
      
      - name: Package dist directory
        run: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::CreateFromDirectory('dist', 'starmap.zip')

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: starmap.zip
